module ColorSpeak.App {
    function renderItem(item : ColorEntry, index : number, totalCount : number) {
        return "<div class='item' aria-setsize='"+totalCount+"' aria-posinset='"+index + "' role='listitem'><div class='swatch' style='background-color:" + item.hexCode + "'></div><div class='name'>" + item.name + " " + item.hexCode +"</div></div>";
    }

    window.addEventListener("load", function() {
        var colorSelect = <HTMLSelectElement>document.getElementById('colorSelect');
        var colorText = <HTMLInputElement>document.getElementById('colorText');
        var summary = <HTMLInputElement>document.getElementById('summary');
        var foreground = <HTMLElement>document.getElementById('foreground');

        function updateDisplay(match? : string) {
            var colors = getColors(match);
            var colorsForSelect = colors.reduce(function(result, item, index) {
                return result + renderItem(item, index, colors.length);
            }, "");
            colorSelect.innerHTML = colorsForSelect;
            Array.prototype.forEach.call(colorSelect.children,
                (item) => makeListItem(
                    item,
                    [colorSelect],
                    (e) => { foreground.style.backgroundColor = (<HTMLElement>(e.querySelector(".swatch"))).style.backgroundColor; }
                )
            );
            summary.textContent = colors.length + ' of 949 matched';
        }
        updateDisplay();

        colorText.onkeyup = (evt) => {
            updateDisplay(colorText.value);
        };
    });

    function makeListItem(
        element : HTMLElement, 
        listScope: NodeList | HTMLElement[], 
        onselected?:(element : HTMLElement)=>void
    ) {
        var pointerDown = false;

        element.tabIndex = 0;
        element.classList.add("listitem");

        function findAllListItems() {
            var result : HTMLElement[] = [];
            Array.prototype.forEach.call(listScope,
                (item) => Array.prototype.forEach.call(item.querySelectorAll(".listitem"), 
                    (i2) => result.push(i2)
                )
            );
            return result;
        }

        function select() {
            if (!element.classList.contains("selected")) {
                findAllListItems().forEach((elem) => elem.classList.remove("selected"));
                element.classList.add("selected");
                onselected && onselected(element);
            }
        }

        element.addEventListener("keydown", (ev) => {
            switch (ev.keyCode) {
                case 35: // end
                    var items = findAllListItems();
                    items[items.length - 1].focus();
                    ev.preventDefault();
                    break;
                case 36: // home
                    var items = findAllListItems();
                    items[0].focus();
                    ev.preventDefault();
                    break;
                case 37: // left
                case 38: // up
                    var items = findAllListItems();
                    var found = items.indexOf(element);
                    if (found > 0) { items[found - 1].focus(); }
                    ev.preventDefault();
                    break;
                case 39: // right
                case 40: // down
                    var items = findAllListItems();
                    var found = items.indexOf(element);
                    if (found < items.length - 1) { items[found + 1].focus(); }
                    ev.preventDefault();
                    break;
            }
        }, false);
        element.addEventListener("focus", (ev) => {
            select();
        });
        element.addEventListener("pointerdown", (ev) => { 
            pointerDown = true;
            element.focus();
        }, true);

        element.addEventListener("pointerup", (ev) => { 
            if (pointerDown) {
                select();
            }
        }, true);
    };
}

module ColorSpeak {
    export function getColors(match? : string) {
        if (match) {
            return rawData.filter(item=> item.name.indexOf(match.toLowerCase()) != -1);
        }
        else {
            return rawData;
        }
    }

    export interface ColorEntry {
        name : string;
        hexCode: string;
    }

    var rawData : ColorEntry[] = [
        // I love XKCD: http://blog.xkcd.com/2010/05/03/color-survey-results/
        // License: http://creativecommons.org/publicdomain/zero/1.0/
        { name: "cloudy blue", hexCode: "#acc2d9" },
        { name: "dark pastel green", hexCode: "#56ae57" },
        { name: "dust", hexCode: "#b2996e" },
        { name: "electric lime", hexCode: "#a8ff04" },
        { name: "fresh green", hexCode: "#69d84f" },
        { name: "light eggplant", hexCode: "#894585" },
        { name: "nasty green", hexCode: "#70b23f" },
        { name: "really light blue", hexCode: "#d4ffff" },
        { name: "tea", hexCode: "#65ab7c" },
        { name: "warm purple", hexCode: "#952e8f" },
        { name: "yellowish tan", hexCode: "#fcfc81" },
        { name: "cement", hexCode: "#a5a391" },
        { name: "dark grass green", hexCode: "#388004" },
        { name: "dusty teal", hexCode: "#4c9085" },
        { name: "grey teal", hexCode: "#5e9b8a" },
        { name: "macaroni and cheese", hexCode: "#efb435" },
        { name: "pinkish tan", hexCode: "#d99b82" },
        { name: "spruce", hexCode: "#0a5f38" },
        { name: "strong blue", hexCode: "#0c06f7" },
        { name: "toxic green", hexCode: "#61de2a" },
        { name: "windows blue", hexCode: "#3778bf" },
        { name: "blue blue", hexCode: "#2242c7" },
        { name: "blue with a hint of purple", hexCode: "#533cc6" },
        { name: "booger", hexCode: "#9bb53c" },
        { name: "bright sea green", hexCode: "#05ffa6" },
        { name: "dark green blue", hexCode: "#1f6357" },
        { name: "deep turquoise", hexCode: "#017374" },
        { name: "green teal", hexCode: "#0cb577" },
        { name: "strong pink", hexCode: "#ff0789" },
        { name: "bland", hexCode: "#afa88b" },
        { name: "deep aqua", hexCode: "#08787f" },
        { name: "lavender pink", hexCode: "#dd85d7" },
        { name: "light moss green", hexCode: "#a6c875" },
        { name: "light seafoam green", hexCode: "#a7ffb5" },
        { name: "olive yellow", hexCode: "#c2b709" },
        { name: "pig pink", hexCode: "#e78ea5" },
        { name: "deep lilac", hexCode: "#966ebd" },
        { name: "desert", hexCode: "#ccad60" },
        { name: "dusty lavender", hexCode: "#ac86a8" },
        { name: "purpley grey", hexCode: "#947e94" },
        { name: "purply", hexCode: "#983fb2" },
        { name: "candy pink", hexCode: "#ff63e9" },
        { name: "light pastel green", hexCode: "#b2fba5" },
        { name: "boring green", hexCode: "#63b365" },
        { name: "kiwi green", hexCode: "#8ee53f" },
        { name: "light grey green", hexCode: "#b7e1a1" },
        { name: "orange pink", hexCode: "#ff6f52" },
        { name: "tea green", hexCode: "#bdf8a3" },
        { name: "very light brown", hexCode: "#d3b683" },
        { name: "egg shell", hexCode: "#fffcc4" },
        { name: "eggplant purple", hexCode: "#430541" },
        { name: "powder pink", hexCode: "#ffb2d0" },
        { name: "reddish grey", hexCode: "#997570" },
        { name: "baby shit brown", hexCode: "#ad900d" },
        { name: "liliac", hexCode: "#c48efd" },
        { name: "stormy blue", hexCode: "#507b9c" },
        { name: "ugly brown", hexCode: "#7d7103" },
        { name: "custard", hexCode: "#fffd78" },
        { name: "darkish pink", hexCode: "#da467d" },
        { name: "deep brown", hexCode: "#410200" },
        { name: "greenish beige", hexCode: "#c9d179" },
        { name: "manilla", hexCode: "#fffa86" },
        { name: "off blue", hexCode: "#5684ae" },
        { name: "battleship grey", hexCode: "#6b7c85" },
        { name: "browny green", hexCode: "#6f6c0a" },
        { name: "bruise", hexCode: "#7e4071" },
        { name: "kelley green", hexCode: "#009337" },
        { name: "sickly yellow", hexCode: "#d0e429" },
        { name: "sunny yellow", hexCode: "#fff917" },
        { name: "azul", hexCode: "#1d5dec" },
        { name: "darkgreen", hexCode: "#054907" },
        { name: "green/yellow", hexCode: "#b5ce08" },
        { name: "lichen", hexCode: "#8fb67b" },
        { name: "light light green", hexCode: "#c8ffb0" },
        { name: "pale gold", hexCode: "#fdde6c" },
        { name: "sun yellow", hexCode: "#ffdf22" },
        { name: "tan green", hexCode: "#a9be70" },
        { name: "burple", hexCode: "#6832e3" },
        { name: "butterscotch", hexCode: "#fdb147" },
        { name: "toupe", hexCode: "#c7ac7d" },
        { name: "dark cream", hexCode: "#fff39a" },
        { name: "indian red", hexCode: "#850e04" },
        { name: "light lavendar", hexCode: "#efc0fe" },
        { name: "poison green", hexCode: "#40fd14" },
        { name: "baby puke green", hexCode: "#b6c406" },
        { name: "bright yellow green", hexCode: "#9dff00" },
        { name: "charcoal grey", hexCode: "#3c4142" },
        { name: "squash", hexCode: "#f2ab15" },
        { name: "cinnamon", hexCode: "#ac4f06" },
        { name: "light pea green", hexCode: "#c4fe82" },
        { name: "radioactive green", hexCode: "#2cfa1f" },
        { name: "raw sienna", hexCode: "#9a6200" },
        { name: "baby purple", hexCode: "#ca9bf7" },
        { name: "cocoa", hexCode: "#875f42" },
        { name: "light royal blue", hexCode: "#3a2efe" },
        { name: "orangeish", hexCode: "#fd8d49" },
        { name: "rust brown", hexCode: "#8b3103" },
        { name: "sand brown", hexCode: "#cba560" },
        { name: "swamp", hexCode: "#698339" },
        { name: "tealish green", hexCode: "#0cdc73" },
        { name: "burnt siena", hexCode: "#b75203" },
        { name: "camo", hexCode: "#7f8f4e" },
        { name: "dusk blue", hexCode: "#26538d" },
        { name: "fern", hexCode: "#63a950" },
        { name: "old rose", hexCode: "#c87f89" },
        { name: "pale light green", hexCode: "#b1fc99" },
        { name: "peachy pink", hexCode: "#ff9a8a" },
        { name: "rosy pink", hexCode: "#f6688e" },
        { name: "light bluish green", hexCode: "#76fda8" },
        { name: "light bright green", hexCode: "#53fe5c" },
        { name: "light neon green", hexCode: "#4efd54" },
        { name: "light seafoam", hexCode: "#a0febf" },
        { name: "tiffany blue", hexCode: "#7bf2da" },
        { name: "washed out green", hexCode: "#bcf5a6" },
        { name: "browny orange", hexCode: "#ca6b02" },
        { name: "nice blue", hexCode: "#107ab0" },
        { name: "sapphire", hexCode: "#2138ab" },
        { name: "greyish teal", hexCode: "#719f91" },
        { name: "orangey yellow", hexCode: "#fdb915" },
        { name: "parchment", hexCode: "#fefcaf" },
        { name: "straw", hexCode: "#fcf679" },
        { name: "very dark brown", hexCode: "#1d0200" },
        { name: "terracota", hexCode: "#cb6843" },
        { name: "ugly blue", hexCode: "#31668a" },
        { name: "clear blue", hexCode: "#247afd" },
        { name: "creme", hexCode: "#ffffb6" },
        { name: "foam green", hexCode: "#90fda9" },
        { name: "grey/green", hexCode: "#86a17d" },
        { name: "light gold", hexCode: "#fddc5c" },
        { name: "seafoam blue", hexCode: "#78d1b6" },
        { name: "topaz", hexCode: "#13bbaf" },
        { name: "violet pink", hexCode: "#fb5ffc" },
        { name: "wintergreen", hexCode: "#20f986" },
        { name: "yellow tan", hexCode: "#ffe36e" },
        { name: "dark fuchsia", hexCode: "#9d0759" },
        { name: "indigo blue", hexCode: "#3a18b1" },
        { name: "light yellowish green", hexCode: "#c2ff89" },
        { name: "pale magenta", hexCode: "#d767ad" },
        { name: "rich purple", hexCode: "#720058" },
        { name: "sunflower yellow", hexCode: "#ffda03" },
        { name: "green/blue", hexCode: "#01c08d" },
        { name: "leather", hexCode: "#ac7434" },
        { name: "racing green", hexCode: "#014600" },
        { name: "vivid purple", hexCode: "#9900fa" },
        { name: "dark royal blue", hexCode: "#02066f" },
        { name: "hazel", hexCode: "#8e7618" },
        { name: "muted pink", hexCode: "#d1768f" },
        { name: "booger green", hexCode: "#96b403" },
        { name: "canary", hexCode: "#fdff63" },
        { name: "cool grey", hexCode: "#95a3a6" },
        { name: "dark taupe", hexCode: "#7f684e" },
        { name: "darkish purple", hexCode: "#751973" },
        { name: "true green", hexCode: "#089404" },
        { name: "coral pink", hexCode: "#ff6163" },
        { name: "dark sage", hexCode: "#598556" },
        { name: "dark slate blue", hexCode: "#214761" },
        { name: "flat blue", hexCode: "#3c73a8" },
        { name: "mushroom", hexCode: "#ba9e88" },
        { name: "rich blue", hexCode: "#021bf9" },
        { name: "dirty purple", hexCode: "#734a65" },
        { name: "greenblue", hexCode: "#23c48b" },
        { name: "icky green", hexCode: "#8fae22" },
        { name: "light khaki", hexCode: "#e6f2a2" },
        { name: "warm blue", hexCode: "#4b57db" },
        { name: "dark hot pink", hexCode: "#d90166" },
        { name: "deep sea blue", hexCode: "#015482" },
        { name: "carmine", hexCode: "#9d0216" },
        { name: "dark yellow green", hexCode: "#728f02" },
        { name: "pale peach", hexCode: "#ffe5ad" },
        { name: "plum purple", hexCode: "#4e0550" },
        { name: "golden rod", hexCode: "#f9bc08" },
        { name: "neon red", hexCode: "#ff073a" },
        { name: "old pink", hexCode: "#c77986" },
        { name: "very pale blue", hexCode: "#d6fffe" },
        { name: "blood orange", hexCode: "#fe4b03" },
        { name: "grapefruit", hexCode: "#fd5956" },
        { name: "sand yellow", hexCode: "#fce166" },
        { name: "clay brown", hexCode: "#b2713d" },
        { name: "dark blue grey", hexCode: "#1f3b4d" },
        { name: "flat green", hexCode: "#699d4c" },
        { name: "light green blue", hexCode: "#56fca2" },
        { name: "warm pink", hexCode: "#fb5581" },
        { name: "dodger blue", hexCode: "#3e82fc" },
        { name: "gross green", hexCode: "#a0bf16" },
        { name: "ice", hexCode: "#d6fffa" },
        { name: "metallic blue", hexCode: "#4f738e" },
        { name: "pale salmon", hexCode: "#ffb19a" },
        { name: "sap green", hexCode: "#5c8b15" },
        { name: "algae", hexCode: "#54ac68" },
        { name: "bluey grey", hexCode: "#89a0b0" },
        { name: "greeny grey", hexCode: "#7ea07a" },
        { name: "highlighter green", hexCode: "#1bfc06" },
        { name: "light light blue", hexCode: "#cafffb" },
        { name: "light mint", hexCode: "#b6ffbb" },
        { name: "raw umber", hexCode: "#a75e09" },
        { name: "vivid blue", hexCode: "#152eff" },
        { name: "deep lavender", hexCode: "#8d5eb7" },
        { name: "dull teal", hexCode: "#5f9e8f" },
        { name: "light greenish blue", hexCode: "#63f7b4" },
        { name: "mud green", hexCode: "#606602" },
        { name: "pinky", hexCode: "#fc86aa" },
        { name: "red wine", hexCode: "#8c0034" },
        { name: "shit green", hexCode: "#758000" },
        { name: "tan brown", hexCode: "#ab7e4c" },
        { name: "darkblue", hexCode: "#030764" },
        { name: "rosa", hexCode: "#fe86a4" },
        { name: "lipstick", hexCode: "#d5174e" },
        { name: "pale mauve", hexCode: "#fed0fc" },
        { name: "claret", hexCode: "#680018" },
        { name: "dandelion", hexCode: "#fedf08" },
        { name: "orangered", hexCode: "#fe420f" },
        { name: "poop green", hexCode: "#6f7c00" },
        { name: "ruby", hexCode: "#ca0147" },
        { name: "dark", hexCode: "#1b2431" },
        { name: "greenish turquoise", hexCode: "#00fbb0" },
        { name: "pastel red", hexCode: "#db5856" },
        { name: "piss yellow", hexCode: "#ddd618" },
        { name: "bright cyan", hexCode: "#41fdfe" },
        { name: "dark coral", hexCode: "#cf524e" },
        { name: "algae green", hexCode: "#21c36f" },
        { name: "darkish red", hexCode: "#a90308" },
        { name: "reddy brown", hexCode: "#6e1005" },
        { name: "blush pink", hexCode: "#fe828c" },
        { name: "camouflage green", hexCode: "#4b6113" },
        { name: "lawn green", hexCode: "#4da409" },
        { name: "putty", hexCode: "#beae8a" },
        { name: "vibrant blue", hexCode: "#0339f8" },
        { name: "dark sand", hexCode: "#a88f59" },
        { name: "purple/blue", hexCode: "#5d21d0" },
        { name: "saffron", hexCode: "#feb209" },
        { name: "twilight", hexCode: "#4e518b" },
        { name: "warm brown", hexCode: "#964e02" },
        { name: "bluegrey", hexCode: "#85a3b2" },
        { name: "bubble gum pink", hexCode: "#ff69af" },
        { name: "duck egg blue", hexCode: "#c3fbf4" },
        { name: "greenish cyan", hexCode: "#2afeb7" },
        { name: "petrol", hexCode: "#005f6a" },
        { name: "royal", hexCode: "#0c1793" },
        { name: "butter", hexCode: "#ffff81" },
        { name: "dusty orange", hexCode: "#f0833a" },
        { name: "off yellow", hexCode: "#f1f33f" },
        { name: "pale olive green", hexCode: "#b1d27b" },
        { name: "orangish", hexCode: "#fc824a" },
        { name: "leaf", hexCode: "#71aa34" },
        { name: "light blue grey", hexCode: "#b7c9e2" },
        { name: "dried blood", hexCode: "#4b0101" },
        { name: "lightish purple", hexCode: "#a552e6" },
        { name: "rusty red", hexCode: "#af2f0d" },
        { name: "lavender blue", hexCode: "#8b88f8" },
        { name: "light grass green", hexCode: "#9af764" },
        { name: "light mint green", hexCode: "#a6fbb2" },
        { name: "sunflower", hexCode: "#ffc512" },
        { name: "velvet", hexCode: "#750851" },
        { name: "brick orange", hexCode: "#c14a09" },
        { name: "lightish red", hexCode: "#fe2f4a" },
        { name: "pure blue", hexCode: "#0203e2" },
        { name: "twilight blue", hexCode: "#0a437a" },
        { name: "violet red", hexCode: "#a50055" },
        { name: "yellowy brown", hexCode: "#ae8b0c" },
        { name: "carnation", hexCode: "#fd798f" },
        { name: "muddy yellow", hexCode: "#bfac05" },
        { name: "dark seafoam green", hexCode: "#3eaf76" },
        { name: "deep rose", hexCode: "#c74767" },
        { name: "dusty red", hexCode: "#b9484e" },
        { name: "grey/blue", hexCode: "#647d8e" },
        { name: "lemon lime", hexCode: "#bffe28" },
        { name: "purple/pink", hexCode: "#d725de" },
        { name: "brown yellow", hexCode: "#b29705" },
        { name: "purple brown", hexCode: "#673a3f" },
        { name: "wisteria", hexCode: "#a87dc2" },
        { name: "banana yellow", hexCode: "#fafe4b" },
        { name: "lipstick red", hexCode: "#c0022f" },
        { name: "water blue", hexCode: "#0e87cc" },
        { name: "brown grey", hexCode: "#8d8468" },
        { name: "vibrant purple", hexCode: "#ad03de" },
        { name: "baby green", hexCode: "#8cff9e" },
        { name: "barf green", hexCode: "#94ac02" },
        { name: "eggshell blue", hexCode: "#c4fff7" },
        { name: "sandy yellow", hexCode: "#fdee73" },
        { name: "cool green", hexCode: "#33b864" },
        { name: "pale", hexCode: "#fff9d0" },
        { name: "blue/grey", hexCode: "#758da3" },
        { name: "hot magenta", hexCode: "#f504c9" },
        { name: "greyblue", hexCode: "#77a1b5" },
        { name: "purpley", hexCode: "#8756e4" },
        { name: "baby shit green", hexCode: "#889717" },
        { name: "brownish pink", hexCode: "#c27e79" },
        { name: "dark aquamarine", hexCode: "#017371" },
        { name: "diarrhea", hexCode: "#9f8303" },
        { name: "light mustard", hexCode: "#f7d560" },
        { name: "pale sky blue", hexCode: "#bdf6fe" },
        { name: "turtle green", hexCode: "#75b84f" },
        { name: "bright olive", hexCode: "#9cbb04" },
        { name: "dark grey blue", hexCode: "#29465b" },
        { name: "greeny brown", hexCode: "#696006" },
        { name: "lemon green", hexCode: "#adf802" },
        { name: "light periwinkle", hexCode: "#c1c6fc" },
        { name: "seaweed green", hexCode: "#35ad6b" },
        { name: "sunshine yellow", hexCode: "#fffd37" },
        { name: "ugly purple", hexCode: "#a442a0" },
        { name: "medium pink", hexCode: "#f36196" },
        { name: "puke brown", hexCode: "#947706" },
        { name: "very light pink", hexCode: "#fff4f2" },
        { name: "viridian", hexCode: "#1e9167" },
        { name: "bile", hexCode: "#b5c306" },
        { name: "faded yellow", hexCode: "#feff7f" },
        { name: "very pale green", hexCode: "#cffdbc" },
        { name: "vibrant green", hexCode: "#0add08" },
        { name: "bright lime", hexCode: "#87fd05" },
        { name: "spearmint", hexCode: "#1ef876" },
        { name: "light aquamarine", hexCode: "#7bfdc7" },
        { name: "light sage", hexCode: "#bcecac" },
        { name: "yellowgreen", hexCode: "#bbf90f" },
        { name: "baby poo", hexCode: "#ab9004" },
        { name: "dark seafoam", hexCode: "#1fb57a" },
        { name: "deep teal", hexCode: "#00555a" },
        { name: "heather", hexCode: "#a484ac" },
        { name: "rust orange", hexCode: "#c45508" },
        { name: "dirty blue", hexCode: "#3f829d" },
        { name: "fern green", hexCode: "#548d44" },
        { name: "bright lilac", hexCode: "#c95efb" },
        { name: "weird green", hexCode: "#3ae57f" },
        { name: "peacock blue", hexCode: "#016795" },
        { name: "avocado green", hexCode: "#87a922" },
        { name: "faded orange", hexCode: "#f0944d" },
        { name: "grape purple", hexCode: "#5d1451" },
        { name: "hot green", hexCode: "#25ff29" },
        { name: "lime yellow", hexCode: "#d0fe1d" },
        { name: "mango", hexCode: "#ffa62b" },
        { name: "shamrock", hexCode: "#01b44c" },
        { name: "bubblegum", hexCode: "#ff6cb5" },
        { name: "purplish brown", hexCode: "#6b4247" },
        { name: "vomit yellow", hexCode: "#c7c10c" },
        { name: "pale cyan", hexCode: "#b7fffa" },
        { name: "key lime", hexCode: "#aeff6e" },
        { name: "tomato red", hexCode: "#ec2d01" },
        { name: "lightgreen", hexCode: "#76ff7b" },
        { name: "merlot", hexCode: "#730039" },
        { name: "night blue", hexCode: "#040348" },
        { name: "purpleish pink", hexCode: "#df4ec8" },
        { name: "apple", hexCode: "#6ecb3c" },
        { name: "baby poop green", hexCode: "#8f9805" },
        { name: "green apple", hexCode: "#5edc1f" },
        { name: "heliotrope", hexCode: "#d94ff5" },
        { name: "yellow/green", hexCode: "#c8fd3d" },
        { name: "almost black", hexCode: "#070d0d" },
        { name: "cool blue", hexCode: "#4984b8" },
        { name: "leafy green", hexCode: "#51b73b" },
        { name: "mustard brown", hexCode: "#ac7e04" },
        { name: "dusk", hexCode: "#4e5481" },
        { name: "dull brown", hexCode: "#876e4b" },
        { name: "frog green", hexCode: "#58bc08" },
        { name: "vivid green", hexCode: "#2fef10" },
        { name: "bright light green", hexCode: "#2dfe54" },
        { name: "fluro green", hexCode: "#0aff02" },
        { name: "kiwi", hexCode: "#9cef43" },
        { name: "seaweed", hexCode: "#18d17b" },
        { name: "navy green", hexCode: "#35530a" },
        { name: "ultramarine blue", hexCode: "#1805db" },
        { name: "iris", hexCode: "#6258c4" },
        { name: "pastel orange", hexCode: "#ff964f" },
        { name: "yellowish orange", hexCode: "#ffab0f" },
        { name: "perrywinkle", hexCode: "#8f8ce7" },
        { name: "tealish", hexCode: "#24bca8" },
        { name: "dark plum", hexCode: "#3f012c" },
        { name: "pear", hexCode: "#cbf85f" },
        { name: "pinkish orange", hexCode: "#ff724c" },
        { name: "midnight purple", hexCode: "#280137" },
        { name: "light urple", hexCode: "#b36ff6" },
        { name: "dark mint", hexCode: "#48c072" },
        { name: "greenish tan", hexCode: "#bccb7a" },
        { name: "light burgundy", hexCode: "#a8415b" },
        { name: "turquoise blue", hexCode: "#06b1c4" },
        { name: "ugly pink", hexCode: "#cd7584" },
        { name: "sandy", hexCode: "#f1da7a" },
        { name: "electric pink", hexCode: "#ff0490" },
        { name: "muted purple", hexCode: "#805b87" },
        { name: "mid green", hexCode: "#50a747" },
        { name: "greyish", hexCode: "#a8a495" },
        { name: "neon yellow", hexCode: "#cfff04" },
        { name: "banana", hexCode: "#ffff7e" },
        { name: "carnation pink", hexCode: "#ff7fa7" },
        { name: "tomato", hexCode: "#ef4026" },
        { name: "sea", hexCode: "#3c9992" },
        { name: "muddy brown", hexCode: "#886806" },
        { name: "turquoise green", hexCode: "#04f489" },
        { name: "buff", hexCode: "#fef69e" },
        { name: "fawn", hexCode: "#cfaf7b" },
        { name: "muted blue", hexCode: "#3b719f" },
        { name: "pale rose", hexCode: "#fdc1c5" },
        { name: "dark mint green", hexCode: "#20c073" },
        { name: "amethyst", hexCode: "#9b5fc0" },
        { name: "blue/green", hexCode: "#0f9b8e" },
        { name: "chestnut", hexCode: "#742802" },
        { name: "sick green", hexCode: "#9db92c" },
        { name: "pea", hexCode: "#a4bf20" },
        { name: "rusty orange", hexCode: "#cd5909" },
        { name: "stone", hexCode: "#ada587" },
        { name: "rose red", hexCode: "#be013c" },
        { name: "pale aqua", hexCode: "#b8ffeb" },
        { name: "deep orange", hexCode: "#dc4d01" },
        { name: "earth", hexCode: "#a2653e" },
        { name: "mossy green", hexCode: "#638b27" },
        { name: "grassy green", hexCode: "#419c03" },
        { name: "pale lime green", hexCode: "#b1ff65" },
        { name: "light grey blue", hexCode: "#9dbcd4" },
        { name: "pale grey", hexCode: "#fdfdfe" },
        { name: "asparagus", hexCode: "#77ab56" },
        { name: "blueberry", hexCode: "#464196" },
        { name: "purple red", hexCode: "#990147" },
        { name: "pale lime", hexCode: "#befd73" },
        { name: "greenish teal", hexCode: "#32bf84" },
        { name: "caramel", hexCode: "#af6f09" },
        { name: "deep magenta", hexCode: "#a0025c" },
        { name: "light peach", hexCode: "#ffd8b1" },
        { name: "milk chocolate", hexCode: "#7f4e1e" },
        { name: "ocher", hexCode: "#bf9b0c" },
        { name: "off green", hexCode: "#6ba353" },
        { name: "purply pink", hexCode: "#f075e6" },
        { name: "lightblue", hexCode: "#7bc8f6" },
        { name: "dusky blue", hexCode: "#475f94" },
        { name: "golden", hexCode: "#f5bf03" },
        { name: "light beige", hexCode: "#fffeb6" },
        { name: "butter yellow", hexCode: "#fffd74" },
        { name: "dusky purple", hexCode: "#895b7b" },
        { name: "french blue", hexCode: "#436bad" },
        { name: "ugly yellow", hexCode: "#d0c101" },
        { name: "greeny yellow", hexCode: "#c6f808" },
        { name: "orangish red", hexCode: "#f43605" },
        { name: "shamrock green", hexCode: "#02c14d" },
        { name: "orangish brown", hexCode: "#b25f03" },
        { name: "tree green", hexCode: "#2a7e19" },
        { name: "deep violet", hexCode: "#490648" },
        { name: "gunmetal", hexCode: "#536267" },
        { name: "blue/purple", hexCode: "#5a06ef" },
        { name: "cherry", hexCode: "#cf0234" },
        { name: "sandy brown", hexCode: "#c4a661" },
        { name: "warm grey", hexCode: "#978a84" },
        { name: "dark indigo", hexCode: "#1f0954" },
        { name: "midnight", hexCode: "#03012d" },
        { name: "bluey green", hexCode: "#2bb179" },
        { name: "grey pink", hexCode: "#c3909b" },
        { name: "soft purple", hexCode: "#a66fb5" },
        { name: "blood", hexCode: "#770001" },
        { name: "brown red", hexCode: "#922b05" },
        { name: "medium grey", hexCode: "#7d7f7c" },
        { name: "berry", hexCode: "#990f4b" },
        { name: "poo", hexCode: "#8f7303" },
        { name: "purpley pink", hexCode: "#c83cb9" },
        { name: "light salmon", hexCode: "#fea993" },
        { name: "snot", hexCode: "#acbb0d" },
        { name: "easter purple", hexCode: "#c071fe" },
        { name: "light yellow green", hexCode: "#ccfd7f" },
        { name: "dark navy blue", hexCode: "#00022e" },
        { name: "drab", hexCode: "#828344" },
        { name: "light rose", hexCode: "#ffc5cb" },
        { name: "rouge", hexCode: "#ab1239" },
        { name: "purplish red", hexCode: "#b0054b" },
        { name: "slime green", hexCode: "#99cc04" },
        { name: "baby poop", hexCode: "#937c00" },
        { name: "irish green", hexCode: "#019529" },
        { name: "pink/purple", hexCode: "#ef1de7" },
        { name: "dark navy", hexCode: "#000435" },
        { name: "greeny blue", hexCode: "#42b395" },
        { name: "light plum", hexCode: "#9d5783" },
        { name: "pinkish grey", hexCode: "#c8aca9" },
        { name: "dirty orange", hexCode: "#c87606" },
        { name: "rust red", hexCode: "#aa2704" },
        { name: "pale lilac", hexCode: "#e4cbff" },
        { name: "orangey red", hexCode: "#fa4224" },
        { name: "primary blue", hexCode: "#0804f9" },
        { name: "kermit green", hexCode: "#5cb200" },
        { name: "brownish purple", hexCode: "#76424e" },
        { name: "murky green", hexCode: "#6c7a0e" },
        { name: "wheat", hexCode: "#fbdd7e" },
        { name: "very dark purple", hexCode: "#2a0134" },
        { name: "bottle green", hexCode: "#044a05" },
        { name: "watermelon", hexCode: "#fd4659" },
        { name: "deep sky blue", hexCode: "#0d75f8" },
        { name: "fire engine red", hexCode: "#fe0002" },
        { name: "yellow ochre", hexCode: "#cb9d06" },
        { name: "pumpkin orange", hexCode: "#fb7d07" },
        { name: "pale olive", hexCode: "#b9cc81" },
        { name: "light lilac", hexCode: "#edc8ff" },
        { name: "lightish green", hexCode: "#61e160" },
        { name: "carolina blue", hexCode: "#8ab8fe" },
        { name: "mulberry", hexCode: "#920a4e" },
        { name: "shocking pink", hexCode: "#fe02a2" },
        { name: "auburn", hexCode: "#9a3001" },
        { name: "bright lime green", hexCode: "#65fe08" },
        { name: "celadon", hexCode: "#befdb7" },
        { name: "pinkish brown", hexCode: "#b17261" },
        { name: "poo brown", hexCode: "#885f01" },
        { name: "bright sky blue", hexCode: "#02ccfe" },
        { name: "celery", hexCode: "#c1fd95" },
        { name: "dirt brown", hexCode: "#836539" },
        { name: "strawberry", hexCode: "#fb2943" },
        { name: "dark lime", hexCode: "#84b701" },
        { name: "copper", hexCode: "#b66325" },
        { name: "medium brown", hexCode: "#7f5112" },
        { name: "muted green", hexCode: "#5fa052" },
        { name: "robin's egg", hexCode: "#6dedfd" },
        { name: "bright aqua", hexCode: "#0bf9ea" },
        { name: "bright lavender", hexCode: "#c760ff" },
        { name: "ivory", hexCode: "#ffffcb" },
        { name: "very light purple", hexCode: "#f6cefc" },
        { name: "light navy", hexCode: "#155084" },
        { name: "pink red", hexCode: "#f5054f" },
        { name: "olive brown", hexCode: "#645403" },
        { name: "poop brown", hexCode: "#7a5901" },
        { name: "mustard green", hexCode: "#a8b504" },
        { name: "ocean green", hexCode: "#3d9973" },
        { name: "very dark blue", hexCode: "#000133" },
        { name: "dusty green", hexCode: "#76a973" },
        { name: "light navy blue", hexCode: "#2e5a88" },
        { name: "minty green", hexCode: "#0bf77d" },
        { name: "adobe", hexCode: "#bd6c48" },
        { name: "barney", hexCode: "#ac1db8" },
        { name: "jade green", hexCode: "#2baf6a" },
        { name: "bright light blue", hexCode: "#26f7fd" },
        { name: "light lime", hexCode: "#aefd6c" },
        { name: "dark khaki", hexCode: "#9b8f55" },
        { name: "orange yellow", hexCode: "#ffad01" },
        { name: "ocre", hexCode: "#c69c04" },
        { name: "maize", hexCode: "#f4d054" },
        { name: "faded pink", hexCode: "#de9dac" },
        { name: "british racing green", hexCode: "#05480d" },
        { name: "sandstone", hexCode: "#c9ae74" },
        { name: "mud brown", hexCode: "#60460f" },
        { name: "light sea green", hexCode: "#98f6b0" },
        { name: "robin egg blue", hexCode: "#8af1fe" },
        { name: "aqua marine", hexCode: "#2ee8bb" },
        { name: "dark sea green", hexCode: "#11875d" },
        { name: "soft pink", hexCode: "#fdb0c0" },
        { name: "orangey brown", hexCode: "#b16002" },
        { name: "cherry red", hexCode: "#f7022a" },
        { name: "burnt yellow", hexCode: "#d5ab09" },
        { name: "brownish grey", hexCode: "#86775f" },
        { name: "camel", hexCode: "#c69f59" },
        { name: "purplish grey", hexCode: "#7a687f" },
        { name: "marine", hexCode: "#042e60" },
        { name: "greyish pink", hexCode: "#c88d94" },
        { name: "pale turquoise", hexCode: "#a5fbd5" },
        { name: "pastel yellow", hexCode: "#fffe71" },
        { name: "bluey purple", hexCode: "#6241c7" },
        { name: "canary yellow", hexCode: "#fffe40" },
        { name: "faded red", hexCode: "#d3494e" },
        { name: "sepia", hexCode: "#985e2b" },
        { name: "coffee", hexCode: "#a6814c" },
        { name: "bright magenta", hexCode: "#ff08e8" },
        { name: "mocha", hexCode: "#9d7651" },
        { name: "ecru", hexCode: "#feffca" },
        { name: "purpleish", hexCode: "#98568d" },
        { name: "cranberry", hexCode: "#9e003a" },
        { name: "darkish green", hexCode: "#287c37" },
        { name: "brown orange", hexCode: "#b96902" },
        { name: "dusky rose", hexCode: "#ba6873" },
        { name: "melon", hexCode: "#ff7855" },
        { name: "sickly green", hexCode: "#94b21c" },
        { name: "silver", hexCode: "#c5c9c7" },
        { name: "purply blue", hexCode: "#661aee" },
        { name: "purpleish blue", hexCode: "#6140ef" },
        { name: "hospital green", hexCode: "#9be5aa" },
        { name: "shit brown", hexCode: "#7b5804" },
        { name: "mid blue", hexCode: "#276ab3" },
        { name: "amber", hexCode: "#feb308" },
        { name: "easter green", hexCode: "#8cfd7e" },
        { name: "soft blue", hexCode: "#6488ea" },
        { name: "cerulean blue", hexCode: "#056eee" },
        { name: "golden brown", hexCode: "#b27a01" },
        { name: "bright turquoise", hexCode: "#0ffef9" },
        { name: "red pink", hexCode: "#fa2a55" },
        { name: "red purple", hexCode: "#820747" },
        { name: "greyish brown", hexCode: "#7a6a4f" },
        { name: "vermillion", hexCode: "#f4320c" },
        { name: "russet", hexCode: "#a13905" },
        { name: "steel grey", hexCode: "#6f828a" },
        { name: "lighter purple", hexCode: "#a55af4" },
        { name: "bright violet", hexCode: "#ad0afd" },
        { name: "prussian blue", hexCode: "#004577" },
        { name: "slate green", hexCode: "#658d6d" },
        { name: "dirty pink", hexCode: "#ca7b80" },
        { name: "dark blue green", hexCode: "#005249" },
        { name: "pine", hexCode: "#2b5d34" },
        { name: "yellowy green", hexCode: "#bff128" },
        { name: "dark gold", hexCode: "#b59410" },
        { name: "bluish", hexCode: "#2976bb" },
        { name: "darkish blue", hexCode: "#014182" },
        { name: "dull red", hexCode: "#bb3f3f" },
        { name: "pinky red", hexCode: "#fc2647" },
        { name: "bronze", hexCode: "#a87900" },
        { name: "pale teal", hexCode: "#82cbb2" },
        { name: "military green", hexCode: "#667c3e" },
        { name: "barbie pink", hexCode: "#fe46a5" },
        { name: "bubblegum pink", hexCode: "#fe83cc" },
        { name: "pea soup green", hexCode: "#94a617" },
        { name: "dark mustard", hexCode: "#a88905" },
        { name: "shit", hexCode: "#7f5f00" },
        { name: "medium purple", hexCode: "#9e43a2" },
        { name: "very dark green", hexCode: "#062e03" },
        { name: "dirt", hexCode: "#8a6e45" },
        { name: "dusky pink", hexCode: "#cc7a8b" },
        { name: "red violet", hexCode: "#9e0168" },
        { name: "lemon yellow", hexCode: "#fdff38" },
        { name: "pistachio", hexCode: "#c0fa8b" },
        { name: "dull yellow", hexCode: "#eedc5b" },
        { name: "dark lime green", hexCode: "#7ebd01" },
        { name: "denim blue", hexCode: "#3b5b92" },
        { name: "teal blue", hexCode: "#01889f" },
        { name: "lightish blue", hexCode: "#3d7afd" },
        { name: "purpley blue", hexCode: "#5f34e7" },
        { name: "light indigo", hexCode: "#6d5acf" },
        { name: "swamp green", hexCode: "#748500" },
        { name: "brown green", hexCode: "#706c11" },
        { name: "dark maroon", hexCode: "#3c0008" },
        { name: "hot purple", hexCode: "#cb00f5" },
        { name: "dark forest green", hexCode: "#002d04" },
        { name: "faded blue", hexCode: "#658cbb" },
        { name: "drab green", hexCode: "#749551" },
        { name: "light lime green", hexCode: "#b9ff66" },
        { name: "snot green", hexCode: "#9dc100" },
        { name: "yellowish", hexCode: "#faee66" },
        { name: "light blue green", hexCode: "#7efbb3" },
        { name: "bordeaux", hexCode: "#7b002c" },
        { name: "light mauve", hexCode: "#c292a1" },
        { name: "ocean", hexCode: "#017b92" },
        { name: "marigold", hexCode: "#fcc006" },
        { name: "muddy green", hexCode: "#657432" },
        { name: "dull orange", hexCode: "#d8863b" },
        { name: "steel", hexCode: "#738595" },
        { name: "electric purple", hexCode: "#aa23ff" },
        { name: "fluorescent green", hexCode: "#08ff08" },
        { name: "yellowish brown", hexCode: "#9b7a01" },
        { name: "blush", hexCode: "#f29e8e" },
        { name: "soft green", hexCode: "#6fc276" },
        { name: "bright orange", hexCode: "#ff5b00" },
        { name: "lemon", hexCode: "#fdff52" },
        { name: "purple grey", hexCode: "#866f85" },
        { name: "acid green", hexCode: "#8ffe09" },
        { name: "pale lavender", hexCode: "#eecffe" },
        { name: "violet blue", hexCode: "#510ac9" },
        { name: "light forest green", hexCode: "#4f9153" },
        { name: "burnt red", hexCode: "#9f2305" },
        { name: "khaki green", hexCode: "#728639" },
        { name: "cerise", hexCode: "#de0c62" },
        { name: "faded purple", hexCode: "#916e99" },
        { name: "apricot", hexCode: "#ffb16d" },
        { name: "dark olive green", hexCode: "#3c4d03" },
        { name: "grey brown", hexCode: "#7f7053" },
        { name: "green grey", hexCode: "#77926f" },
        { name: "true blue", hexCode: "#010fcc" },
        { name: "pale violet", hexCode: "#ceaefa" },
        { name: "periwinkle blue", hexCode: "#8f99fb" },
        { name: "light sky blue", hexCode: "#c6fcff" },
        { name: "blurple", hexCode: "#5539cc" },
        { name: "green brown", hexCode: "#544e03" },
        { name: "bluegreen", hexCode: "#017a79" },
        { name: "bright teal", hexCode: "#01f9c6" },
        { name: "brownish yellow", hexCode: "#c9b003" },
        { name: "pea soup", hexCode: "#929901" },
        { name: "forest", hexCode: "#0b5509" },
        { name: "barney purple", hexCode: "#a00498" },
        { name: "ultramarine", hexCode: "#2000b1" },
        { name: "purplish", hexCode: "#94568c" },
        { name: "puke yellow", hexCode: "#c2be0e" },
        { name: "bluish grey", hexCode: "#748b97" },
        { name: "dark periwinkle", hexCode: "#665fd1" },
        { name: "dark lilac", hexCode: "#9c6da5" },
        { name: "reddish", hexCode: "#c44240" },
        { name: "light maroon", hexCode: "#a24857" },
        { name: "dusty purple", hexCode: "#825f87" },
        { name: "terra cotta", hexCode: "#c9643b" },
        { name: "avocado", hexCode: "#90b134" },
        { name: "marine blue", hexCode: "#01386a" },
        { name: "teal green", hexCode: "#25a36f" },
        { name: "slate grey", hexCode: "#59656d" },
        { name: "lighter green", hexCode: "#75fd63" },
        { name: "electric green", hexCode: "#21fc0d" },
        { name: "dusty blue", hexCode: "#5a86ad" },
        { name: "golden yellow", hexCode: "#fec615" },
        { name: "bright yellow", hexCode: "#fffd01" },
        { name: "light lavender", hexCode: "#dfc5fe" },
        { name: "umber", hexCode: "#b26400" },
        { name: "poop", hexCode: "#7f5e00" },
        { name: "dark peach", hexCode: "#de7e5d" },
        { name: "jungle green", hexCode: "#048243" },
        { name: "eggshell", hexCode: "#ffffd4" },
        { name: "denim", hexCode: "#3b638c" },
        { name: "yellow brown", hexCode: "#b79400" },
        { name: "dull purple", hexCode: "#84597e" },
        { name: "chocolate brown", hexCode: "#411900" },
        { name: "wine red", hexCode: "#7b0323" },
        { name: "neon blue", hexCode: "#04d9ff" },
        { name: "dirty green", hexCode: "#667e2c" },
        { name: "light tan", hexCode: "#fbeeac" },
        { name: "ice blue", hexCode: "#d7fffe" },
        { name: "cadet blue", hexCode: "#4e7496" },
        { name: "dark mauve", hexCode: "#874c62" },
        { name: "very light blue", hexCode: "#d5ffff" },
        { name: "grey purple", hexCode: "#826d8c" },
        { name: "pastel pink", hexCode: "#ffbacd" },
        { name: "very light green", hexCode: "#d1ffbd" },
        { name: "dark sky blue", hexCode: "#448ee4" },
        { name: "evergreen", hexCode: "#05472a" },
        { name: "dull pink", hexCode: "#d5869d" },
        { name: "aubergine", hexCode: "#3d0734" },
        { name: "mahogany", hexCode: "#4a0100" },
        { name: "reddish orange", hexCode: "#f8481c" },
        { name: "deep green", hexCode: "#02590f" },
        { name: "vomit green", hexCode: "#89a203" },
        { name: "purple pink", hexCode: "#e03fd8" },
        { name: "dusty pink", hexCode: "#d58a94" },
        { name: "faded green", hexCode: "#7bb274" },
        { name: "camo green", hexCode: "#526525" },
        { name: "pinky purple", hexCode: "#c94cbe" },
        { name: "pink purple", hexCode: "#db4bda" },
        { name: "brownish red", hexCode: "#9e3623" },
        { name: "dark rose", hexCode: "#b5485d" },
        { name: "mud", hexCode: "#735c12" },
        { name: "brownish", hexCode: "#9c6d57" },
        { name: "emerald green", hexCode: "#028f1e" },
        { name: "pale brown", hexCode: "#b1916e" },
        { name: "dull blue", hexCode: "#49759c" },
        { name: "burnt umber", hexCode: "#a0450e" },
        { name: "medium green", hexCode: "#39ad48" },
        { name: "clay", hexCode: "#b66a50" },
        { name: "light aqua", hexCode: "#8cffdb" },
        { name: "light olive green", hexCode: "#a4be5c" },
        { name: "brownish orange", hexCode: "#cb7723" },
        { name: "dark aqua", hexCode: "#05696b" },
        { name: "purplish pink", hexCode: "#ce5dae" },
        { name: "dark salmon", hexCode: "#c85a53" },
        { name: "greenish grey", hexCode: "#96ae8d" },
        { name: "jade", hexCode: "#1fa774" },
        { name: "ugly green", hexCode: "#7a9703" },
        { name: "dark beige", hexCode: "#ac9362" },
        { name: "emerald", hexCode: "#01a049" },
        { name: "pale red", hexCode: "#d9544d" },
        { name: "light magenta", hexCode: "#fa5ff7" },
        { name: "sky", hexCode: "#82cafc" },
        { name: "light cyan", hexCode: "#acfffc" },
        { name: "yellow orange", hexCode: "#fcb001" },
        { name: "reddish purple", hexCode: "#910951" },
        { name: "reddish pink", hexCode: "#fe2c54" },
        { name: "orchid", hexCode: "#c875c4" },
        { name: "dirty yellow", hexCode: "#cdc50a" },
        { name: "orange red", hexCode: "#fd411e" },
        { name: "deep red", hexCode: "#9a0200" },
        { name: "orange brown", hexCode: "#be6400" },
        { name: "cobalt blue", hexCode: "#030aa7" },
        { name: "neon pink", hexCode: "#fe019a" },
        { name: "rose pink", hexCode: "#f7879a" },
        { name: "greyish purple", hexCode: "#887191" },
        { name: "raspberry", hexCode: "#b00149" },
        { name: "aqua green", hexCode: "#12e193" },
        { name: "salmon pink", hexCode: "#fe7b7c" },
        { name: "tangerine", hexCode: "#ff9408" },
        { name: "brownish green", hexCode: "#6a6e09" },
        { name: "red brown", hexCode: "#8b2e16" },
        { name: "greenish brown", hexCode: "#696112" },
        { name: "pumpkin", hexCode: "#e17701" },
        { name: "pine green", hexCode: "#0a481e" },
        { name: "charcoal", hexCode: "#343837" },
        { name: "baby pink", hexCode: "#ffb7ce" },
        { name: "cornflower", hexCode: "#6a79f7" },
        { name: "blue violet", hexCode: "#5d06e9" },
        { name: "chocolate", hexCode: "#3d1c02" },
        { name: "greyish green", hexCode: "#82a67d" },
        { name: "scarlet", hexCode: "#be0119" },
        { name: "green yellow", hexCode: "#c9ff27" },
        { name: "dark olive", hexCode: "#373e02" },
        { name: "sienna", hexCode: "#a9561e" },
        { name: "pastel purple", hexCode: "#caa0ff" },
        { name: "terracotta", hexCode: "#ca6641" },
        { name: "aqua blue", hexCode: "#02d8e9" },
        { name: "sage green", hexCode: "#88b378" },
        { name: "blood red", hexCode: "#980002" },
        { name: "deep pink", hexCode: "#cb0162" },
        { name: "grass", hexCode: "#5cac2d" },
        { name: "moss", hexCode: "#769958" },
        { name: "pastel blue", hexCode: "#a2bffe" },
        { name: "bluish green", hexCode: "#10a674" },
        { name: "green blue", hexCode: "#06b48b" },
        { name: "dark tan", hexCode: "#af884a" },
        { name: "greenish blue", hexCode: "#0b8b87" },
        { name: "pale orange", hexCode: "#ffa756" },
        { name: "vomit", hexCode: "#a2a415" },
        { name: "forrest green", hexCode: "#154406" },
        { name: "dark lavender", hexCode: "#856798" },
        { name: "dark violet", hexCode: "#34013f" },
        { name: "purple blue", hexCode: "#632de9" },
        { name: "dark cyan", hexCode: "#0a888a" },
        { name: "olive drab", hexCode: "#6f7632" },
        { name: "pinkish", hexCode: "#d46a7e" },
        { name: "cobalt", hexCode: "#1e488f" },
        { name: "neon purple", hexCode: "#bc13fe" },
        { name: "light turquoise", hexCode: "#7ef4cc" },
        { name: "apple green", hexCode: "#76cd26" },
        { name: "dull green", hexCode: "#74a662" },
        { name: "wine", hexCode: "#80013f" },
        { name: "powder blue", hexCode: "#b1d1fc" },
        { name: "off white", hexCode: "#ffffe4" },
        { name: "electric blue", hexCode: "#0652ff" },
        { name: "dark turquoise", hexCode: "#045c5a" },
        { name: "blue purple", hexCode: "#5729ce" },
        { name: "azure", hexCode: "#069af3" },
        { name: "bright red", hexCode: "#ff000d" },
        { name: "pinkish red", hexCode: "#f10c45" },
        { name: "cornflower blue", hexCode: "#5170d7" },
        { name: "light olive", hexCode: "#acbf69" },
        { name: "grape", hexCode: "#6c3461" },
        { name: "greyish blue", hexCode: "#5e819d" },
        { name: "purplish blue", hexCode: "#601ef9" },
        { name: "yellowish green", hexCode: "#b0dd16" },
        { name: "greenish yellow", hexCode: "#cdfd02" },
        { name: "medium blue", hexCode: "#2c6fbb" },
        { name: "dusty rose", hexCode: "#c0737a" },
        { name: "light violet", hexCode: "#d6b4fc" },
        { name: "midnight blue", hexCode: "#020035" },
        { name: "bluish purple", hexCode: "#703be7" },
        { name: "red orange", hexCode: "#fd3c06" },
        { name: "dark magenta", hexCode: "#960056" },
        { name: "greenish", hexCode: "#40a368" },
        { name: "ocean blue", hexCode: "#03719c" },
        { name: "coral", hexCode: "#fc5a50" },
        { name: "cream", hexCode: "#ffffc2" },
        { name: "reddish brown", hexCode: "#7f2b0a" },
        { name: "burnt sienna", hexCode: "#b04e0f" },
        { name: "brick", hexCode: "#a03623" },
        { name: "sage", hexCode: "#87ae73" },
        { name: "grey green", hexCode: "#789b73" },
        { name: "white", hexCode: "#ffffff" },
        { name: "robin's egg blue", hexCode: "#98eff9" },
        { name: "moss green", hexCode: "#658b38" },
        { name: "steel blue", hexCode: "#5a7d9a" },
        { name: "eggplant", hexCode: "#380835" },
        { name: "light yellow", hexCode: "#fffe7a" },
        { name: "leaf green", hexCode: "#5ca904" },
        { name: "light grey", hexCode: "#d8dcd6" },
        { name: "puke", hexCode: "#a5a502" },
        { name: "pinkish purple", hexCode: "#d648d7" },
        { name: "sea blue", hexCode: "#047495" },
        { name: "pale purple", hexCode: "#b790d4" },
        { name: "slate blue", hexCode: "#5b7c99" },
        { name: "blue grey", hexCode: "#607c8e" },
        { name: "hunter green", hexCode: "#0b4008" },
        { name: "fuchsia", hexCode: "#ed0dd9" },
        { name: "crimson", hexCode: "#8c000f" },
        { name: "pale yellow", hexCode: "#ffff84" },
        { name: "ochre", hexCode: "#bf9005" },
        { name: "mustard yellow", hexCode: "#d2bd0a" },
        { name: "light red", hexCode: "#ff474c" },
        { name: "cerulean", hexCode: "#0485d1" },
        { name: "pale pink", hexCode: "#ffcfdc" },
        { name: "deep blue", hexCode: "#040273" },
        { name: "rust", hexCode: "#a83c09" },
        { name: "light teal", hexCode: "#90e4c1" },
        { name: "slate", hexCode: "#516572" },
        { name: "goldenrod", hexCode: "#fac205" },
        { name: "dark yellow", hexCode: "#d5b60a" },
        { name: "dark grey", hexCode: "#363737" },
        { name: "army green", hexCode: "#4b5d16" },
        { name: "grey blue", hexCode: "#6b8ba4" },
        { name: "seafoam", hexCode: "#80f9ad" },
        { name: "puce", hexCode: "#a57e52" },
        { name: "spring green", hexCode: "#a9f971" },
        { name: "dark orange", hexCode: "#c65102" },
        { name: "sand", hexCode: "#e2ca76" },
        { name: "pastel green", hexCode: "#b0ff9d" },
        { name: "mint", hexCode: "#9ffeb0" },
        { name: "light orange", hexCode: "#fdaa48" },
        { name: "bright pink", hexCode: "#fe01b1" },
        { name: "chartreuse", hexCode: "#c1f80a" },
        { name: "deep purple", hexCode: "#36013f" },
        { name: "dark brown", hexCode: "#341c02" },
        { name: "taupe", hexCode: "#b9a281" },
        { name: "pea green", hexCode: "#8eab12" },
        { name: "puke green", hexCode: "#9aae07" },
        { name: "kelly green", hexCode: "#02ab2e" },
        { name: "seafoam green", hexCode: "#7af9ab" },
        { name: "blue green", hexCode: "#137e6d" },
        { name: "khaki", hexCode: "#aaa662" },
        { name: "burgundy", hexCode: "#610023" },
        { name: "dark teal", hexCode: "#014d4e" },
        { name: "brick red", hexCode: "#8f1402" },
        { name: "royal purple", hexCode: "#4b006e" },
        { name: "plum", hexCode: "#580f41" },
        { name: "mint green", hexCode: "#8fff9f" },
        { name: "gold", hexCode: "#dbb40c" },
        { name: "baby blue", hexCode: "#a2cffe" },
        { name: "yellow green", hexCode: "#c0fb2d" },
        { name: "bright purple", hexCode: "#be03fd" },
        { name: "dark red", hexCode: "#840000" },
        { name: "pale blue", hexCode: "#d0fefe" },
        { name: "grass green", hexCode: "#3f9b0b" },
        { name: "navy", hexCode: "#01153e" },
        { name: "aquamarine", hexCode: "#04d8b2" },
        { name: "burnt orange", hexCode: "#c04e01" },
        { name: "neon green", hexCode: "#0cff0c" },
        { name: "bright blue", hexCode: "#0165fc" },
        { name: "rose", hexCode: "#cf6275" },
        { name: "light pink", hexCode: "#ffd1df" },
        { name: "mustard", hexCode: "#ceb301" },
        { name: "indigo", hexCode: "#380282" },
        { name: "lime", hexCode: "#aaff32" },
        { name: "sea green", hexCode: "#53fca1" },
        { name: "periwinkle", hexCode: "#8e82fe" },
        { name: "dark pink", hexCode: "#cb416b" },
        { name: "olive green", hexCode: "#677a04" },
        { name: "peach", hexCode: "#ffb07c" },
        { name: "pale green", hexCode: "#c7fdb5" },
        { name: "light brown", hexCode: "#ad8150" },
        { name: "hot pink", hexCode: "#ff028d" },
        { name: "black", hexCode: "#000000" },
        { name: "lilac", hexCode: "#cea2fd" },
        { name: "navy blue", hexCode: "#001146" },
        { name: "royal blue", hexCode: "#0504aa" },
        { name: "beige", hexCode: "#e6daa6" },
        { name: "salmon", hexCode: "#ff796c" },
        { name: "olive", hexCode: "#6e750e" },
        { name: "maroon", hexCode: "#650021" },
        { name: "bright green", hexCode: "#01ff07" },
        { name: "dark purple", hexCode: "#35063e" },
        { name: "mauve", hexCode: "#ae7181" },
        { name: "forest green", hexCode: "#06470c" },
        { name: "aqua", hexCode: "#13eac9" },
        { name: "cyan", hexCode: "#00ffff" },
        { name: "tan", hexCode: "#d1b26f" },
        { name: "dark blue", hexCode: "#00035b" },
        { name: "lavender", hexCode: "#c79fef" },
        { name: "turquoise", hexCode: "#06c2ac" },
        { name: "dark green", hexCode: "#033500" },
        { name: "violet", hexCode: "#9a0eea" },
        { name: "light purple", hexCode: "#bf77f6" },
        { name: "lime green", hexCode: "#89fe05" },
        { name: "grey", hexCode: "#929591" },
        { name: "sky blue", hexCode: "#75bbfd" },
        { name: "yellow", hexCode: "#ffff14" },
        { name: "magenta", hexCode: "#c20078" },
        { name: "light green", hexCode: "#96f97b" },
        { name: "orange", hexCode: "#f97306" },
        { name: "teal", hexCode: "#029386" },
        { name: "light blue", hexCode: "#95d0fc" },
        { name: "red", hexCode: "#e50000" },
        { name: "brown", hexCode: "#653700" },
        { name: "pink", hexCode: "#ff81c0" },
        { name: "blue", hexCode: "#0343df" },
        { name: "green", hexCode: "#15b01a" },
        { name: "purple", hexCode: "#7e1e9c" }
    ];
}

